Add Insert image url to Editor and go back history #13
Slid-Team/slid_demo pull request #15
Opened 2021-07-07 07:33 UTC by bleuuue

This PR intends to resolve #13 - adding  Insert image url to Editor and go back history #13

**Before this PR:**
- No way for sending img url in VideoCapture to Editor
- There's no way to use the close-button to back to the previous page

**What this PR Does:**
- Send the Img url in VideoCapture to the Editor
- Make a button to go to the previous page
- Resize the canvas according to the size of the browser

**Outcome**
- img is captured using a button in the Editor
- return to the previous page using close-button

2021-07-08 02:27 UTC, hyun-park requested changes

2021-07-08 02:27 UTC, hyun-park commented on slid-demo-app/src/editor/editor/index.js
> +    console.log("handleInsertImage");
PR 날릴 때는 이런 console.log를 지워주세요!

2021-07-08 02:27 UTC, hyun-park commented on slid-demo-app/src/editor/editorController/index.js
> +  useEffect(() => {}, [captureImgUrl]);
얘는 아무것도 안하는걸로 보이는데 왜 있는거죠~?

2021-07-08 02:27 UTC, hyun-park commented on slid-demo-app/src/editor/editorController/index.js
> +    console.log("captureOneClick");
console.log 지워주세요.

2021-07-08 02:27 UTC, hyun-park commented on slid-demo-app/src/editor/editorController/index.js
> +              setTimeout(insertImage, 10);
얘는 왜 setTimeout을 한거죠?

captureOneClick에서 isCapturingOneClick true됨 
-> `VideoCapture.js`에서 isCapturingOneClick의 값 변경을 listen하고 있다가 true로 변경되면 captureImgUrl 값을 변경함
-> `editor/index.js`에서 handleInsertImage 함수를 실행해서 captureImgUrl 값을 block으로 추가함

이 로직인것 같은데, 만약 캡쳐가 오래걸려서 captureImgUrl이 10ms보다 오래걸리면 이 로직이 작동안하지 않을까요?
캡쳐가 완전히 완료가 됐다는 것이 확인이 된 후에 insertImage를 실행하는 방법을 찾아야할 것으로 보입니다.

2021-07-08 02:28 UTC, hyun-park commented
그리고 PR을 날릴 때에는 최소한의 수정만해서 날려주세요. 지금 전체화면 캡쳐와 영역 지정 캡쳐가 섞여서 PR이 날라온 것으로 보이는데, 이러면 리뷰하는 입장에서 힘들어집니다.

2021-07-08 13:39 UTC, hyun-park approved these changes

2021-07-09 00:31 UTC, shyunju7 approved these changes

2021-07-09 00:33 UTC, CEmmanuelP approved these changes

2021-07-09 00:51 UTC, merged