Feature/video player
Slid-Team/slid_demo pull request #4
Opened 2021-06-29 04:52 UTC by bleuuue

2021.06.29
videoPlayer & videoCapture merged

2021-06-29 13:48 UTC, hyun-park commented
제가 리뷰한 부분들 한번 수정해서 다시 PR 날려주세요! :)

2021-06-30 00:19 UTC, CEmmanuelP commented on slid-demo-app/package.json
> +    "sweetalert2-react": "^0.8.3",
test comment

2021-06-30 00:26 UTC, hyun-park requested changes

2021-06-30 01:40 UTC, hyun-park commented
추가로 `.idea` 파일도 .gitignore 에 추가해주세요!

2021-06-30 02:35 UTC, closed without merging